# Generated by Django 3.2.7 on 2021-09-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210917_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=7, verbose_name='role, either buyer or seller'),
        ),
    ]
