# Generated by Django 3.2.7 on 2021-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='namaToko',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='nama toko'),
        ),
        migrations.AlterField(
            model_name='account',
            name='nomorHP',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='nomor hp'),
        ),
        migrations.AlterField(
            model_name='account',
            name='nomorInduk',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='nomor induk mahasiswa/pegawai'),
        ),
    ]
