# Generated by Django 3.2.7 on 2021-09-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210917_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tipeDagangan',
            field=models.CharField(choices=[('makanan', 'Makanan'), ('minuman', 'Minuman'), ('jajanan', 'Jajanan'), ('campuran', 'Campuran')], max_length=10, null=True, verbose_name='tipe dagangan'),
        ),
    ]
