# Generated by Django 3.2.7 on 2021-11-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('stock', models.PositiveIntegerField()),
                ('description', models.TextField(default='deskripsi', max_length=250)),
                ('category', models.CharField(choices=[('makanan', 'Makanan'), ('minuman', 'Minuman')], default='makanan', max_length=100)),
            ],
        ),
    ]
